#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'etc'
COL = 3

options = { long: false }
OptionParser.new do |opts|
  opts.on('-l') do
    options[:long] = true
  end
end.parse!

def fetch_files
  Dir.glob('*')
end

def permission_string(mode)
  permission_chars = %w[r w x]
  9.times.map do |i|
    mask = 1 << (8 - i)
    (mode & mask).zero? ? '-' : permission_chars[i % 3]
  end.join
end

def make_matrix(files, row, col)
  matrix = Array.new(row) { Array.new(col) }

  (0...files.length).each do |i|
    c, r = i.divmod(row)
    matrix[r][c] = files[i] if c < col
  end

  matrix
end

def make_long_matrix(files)
  link_width = files.map{ |file|
    File.lstat(file).nlink.to_s.length
  }.max

  size_width = files.map{ |file|
    File.lstat(file).size.to_s.length
  }.max

  user_width = files.map{ |file|
    Etc.getpwuid(File.lstat(file).uid).name.length
  }.max

  group_width = files.map{ |file|
    Etc.getgrgid(File.lstat(file).gid).name.length
  }.max

  files.map do |file|
    stat = File.lstat(file)

    user_name = Etc.getpwuid(stat.uid).name
    group_name = Etc.getgrgid(stat.gid).name

    filetype =
      case stat.ftype
      when 'file'
        '-'
      when 'link'
        'l'
      when 'directory'
        'd'
      end

    [
      filetype+permission_string(stat.mode),
      stat.nlink.to_s.rjust(link_width),
      user_name.ljust(user_width),
      group_name.ljust(group_width),
      stat.size.to_s.rjust(size_width),
      stat.mtime.strftime('%b %d %H:%M'),
      file
  end
end

def print_matrix(matrix)
  max_length = matrix.flatten.compact.map(&:length).max || 0

  matrix.each do |row|
    line = row.map do |file|
      next '' if file.nil?

      file.ljust(max_length)
    end.join('   ')

    puts line
  end
end

files = fetch_files

if options[:long]
  total_blocks = files.sum do |file|
    File.lstat(file).blocks
  end

  puts "total #{total_blocks}"

  make_long_matrix(files).each do |line|
    puts line
  end
else
  row = (files.length.to_f / COL).ceil
  matrix = make_matrix(files, row, COL)
  print_matrix(matrix)
end
