#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
COL = 3

options = { all: false }
OptionParser.new do |opts|
  opts.on('-a') do
    options[:all] = true
  end
end.parse!

def fetch_files(all: false)
  if all
    Dir.glob('*', File::FNM_DOTMATCH)
       .reject { |file| %w[. ..].include?(file) }
       .sort
  else
    Dir.glob('*').sort
  end
end

def make_matrix(files, row, col)
  matrix = Array.new(row) { Array.new(col) }

  (0...files.length).each do |i|
    c, r = i.divmod(row)

    matrix[r][c] = files[i] if c < col
  end

  matrix
end

def print_matrix(matrix)
  max_length = matrix.flatten.compact.map(&:length).max || 0

  matrix.each do |row|
    line = row.map do |file|
      next '' if file.nil?

      file.ljust(max_length)
    end.join('   ')

    puts line
  end
end

files = fetch_files(all: options[:all])
row = (files.length.to_f / COL).ceil
matrix = make_matrix(files, row, COL)
print_matrix(matrix)
